### ISSUE TITLE
Could not train on the MNIST case

### ISSUE THREAD

**Issue by Andy-Zou** [NellyElsayed/rgcLSTM#3]
During training, the loss is always maintained at 0.246 and cannot be decreased.But using the original Prednet network structure, it can be trained normally.

**Comment by NellyElsayed** [comment]
We have a record for the entire process showing the training process for MNIST and shows the result for the original and all the combinations of the recurrent component corresponds to all our paper results. Sometimes, if you are using spyder, you need to restart your kernel when you switch from run one code to another, such issue we had but running another code. Or you can select remove all variables instead of restart the kernel
